#!/bin/bash

# Icon list
for i in folder-activities.svg folder-bookmark.svg folder-cloud.svg folder-comic.svg folder-decrypted.svg folder-development.svg folder-documents.svg folder-download.svg folder-encrypted.svg folder-favorites.svg folder-gdrive.svg folder-html.svg folder-image-people.svg folder-important.svg folder-locked.svg folder-mail.svg folder-network.svg folder-open.svg folder-pictures.svg folder-print.svg folder-publicshare.svg folder-sound.svg folder-tar.svg folder-templates.svg folder-temp.svg folder-text.svg folder-unlocked.svg folder-videos.svg network-workgroup.svg user-home.svg folder-dropbox.svg folder-owncloud.svg folder-onedrive.svg folder.svg; do

# Start icon
    echo '<svg width="24" height="24" fill="none" version="1.1" xmlns="http://www.w3.org/2000/svg">
<defs><style id="current-color-scheme" type="text/css">.ColorScheme-Highlight {color:#3584e4;}</style></defs>
<rect class="ColorScheme-Highlight" x="1.0201" y=".94865" width="22.013" height="22.048" rx="6.4695" ry="6.4695" style="fill:currentColor;opacity:.7;vector-effect:non-scaling-stroke"/>
<rect x="3" y="2" width="18" height="18" rx="4.4" fill="url(#b)" fill-opacity=".875" opacity=".125" style="fill-opacity:1;fill:#000000;opacity:.06"/>
<rect x="2.9362" y="2.9362" width="18.071" height="18.072" rx="4.1205" ry="4.1205" opacity="0.8" style="fill:#e6e6e6;vector-effect:non-scaling-stroke"/>
<path d="m1 8.2626c-0.056293-1.7083 1.5647-3.2161 3.2943-3.0368 1.4979 0.019558 2.9995-0.042974 4.4947 0.038983 2.0349 0.15394 3.2592 2.337 5.4127 2.072 2.0315 0.00992 4.0643-0.020192 6.095 0.015701 1.6547 0.13326 2.8782 1.7631 2.7033 3.3574-0.01887 2.0964 0.0401 4.1953-0.03405 6.2899-0.24582 3.0703-2.9158 5.769-6.057 5.9551-3.1588 0.04264-6.3197 0.01021-9.4793 0.01722-3.1473-0.021784-5.9533-2.5852-6.3526-5.6391-0.14767-1.6399-0.046179-3.2922-0.076487-4.9378-1.71e-4 -1.3775-3.42e-4 -2.755-5.13e-4 -4.1326z" fill="url(#c)" fill-opacity=".75" opacity=".25" style="fill-opacity:1;fill:#000000;opacity:.1"/>
<path class="ColorScheme-Highlight" d="M23 11.032a3.01 3.01 0 0 0-3.008-3.008h-5.929a4.74 4.74 0 0 1-2.922-1.012A4.74 4.74 0 0 0 8.218 6h-4.21A3.01 3.01 0 0 0 1 9.008V16.4C1 20.056 3.944 23 7.6 23h8.8a6.585 6.585 0 0 0 6.6-6.594z" style="fill:currentColor;opacity:.65"/>' > $i
 

    # Add icon from symbolic folder changing size and color
    if [[ $i != folder.svg ]]; then
        grep path "../../16/places/$i" | sed -E 's|style="[^"]*"|style="fill:currentColor;opacity:0.8" id="icon" transform="translate(8, 11) scale(0.5)" class="ColorScheme-Text"|g' | sed -E 's|fill="#dedede"|style="fill:currentColor;opacity:0.7" id="icon" transform="translate(8, 11) scale(0.5)" class="ColorScheme-Text"|g' | sed 's|class="ColorScheme-Text" class="ColorScheme-Text"|class="ColorScheme-Text"|g' | sed 's|class="ColorScheme-Text"/>|/>|g;s|id="path4139"||g' >> $i
    fi
    echo '</svg>' >> $i
done
 
# Links to folders 
ln -sf folder-download.svg folder-downloads.svg
ln -sf folder-html.svg folder_html.svg
ln -sf folder-pictures.svg folder-images.svg
ln -sf folder-pictures.svg folder-image.svg
ln -sf folder-pictures.svg folder-picture.svg
ln -sf folder-publicshare.svg folder-public.svg
ln -sf folder-temp.svg folder-recent.svg
ln -sf folder-html.svg folder-remote.svg
ln -sf folder-text.svg folder-txt.svg
ln -sf folder-sound.svg folder-music.svg
ln -sf folder-videos.svg folder-video.svg
ln -sf folder-music.svg library-music.svg
ln -sf network-workgroup.svg network-server.svg
ln -sf folder.svg stock_folder.svg
ln -sf folder-locked.svg certificate-server.svg
ln -sf desktop.svg user-desktop.svg
ln -sf folder-favorites.svg favorites.svg
ln -sf folder.svg inode-directory.svg





sed 's|#181818|#4092ec|g' folder-black.svg > folder-blue.svg
sed 's|#181818|#2da3c8|g' folder-black.svg > folder-cyan.svg
sed 's|#181818|#ff0000|g' folder-black.svg > folder-red.svg
sed 's|#181818|#e86f52|g' folder-black.svg > folder-orange.svg
sed 's|#181818|#b5006a|g' folder-black.svg > folder-magenta.svg
sed 's|#181818|#79c479|g' folder-black.svg > folder-green.svg
sed 's|#181818|#a4a4a4|g' folder-black.svg > folder-grey.svg
sed 's|#181818|#5a65b2|g' folder-black.svg > folder-violet.svg
sed 's|#181818|#f7d33a|g' folder-black.svg > folder-yellow.svg
sed 's|#181818|#b8a571|g' folder-black.svg > folder-brown.svg
sed 's|#181818|#e9aada|g' folder-black.svg > folder-pink.svg



# Colored folders
# folder-black.svg
# folder-blue.svg
# folder-cyan.svg
# folder-red.svg
# folder-orange.svg
# folder-magenta.svg
# folder-green.svg
# folder-grey.svg
# folder-violet.svg
# folder-yellow.svg
# folder-brown.svg
